sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t hrektts/plantuml .

script:
  - docker run --rm -it hrektts/plantuml plantuml -version
  - docker run -u 1000:1000 --rm -it hrektts/plantuml plantuml -version
